### ISSUE TITLE
SAE报错

### ISSUE THREAD

**Issue by tolerious** [whtsky/WeRoBot-SAE-demo#3]
按照你的配置，上传到了我的SAE上面后，访问我的SAE url报如下的错误：

```
Traceback (most recent call last):
  File "/data1/www/htdocs/74/testwechatrb/1/index.wsgi", line 2, in <module>
    from robot import robot
  File "/data1/www/htdocs/74/testwechatrb/1/robot.py", line 10, in <module>
    robot = werobot.WeRoBot(token='mytoken')
AttributeError: 'module' object has no attribute 'WeRoBot'
```

**Comment by zct** [comment]
我刚也碰到了这个问题，请问你已经解决了吗?

**Comment by tolerious** [comment]
木有～

**Comment by zct** [comment]
我看看在sae中怎么查看调试信息，本地运行不会报错....

**Comment by tolerious** [comment]
看完了贴下解决办法，我最近没在看这个，在忙别的

**Comment by zct** [comment]
只定位到错误，还没找到解决办法。
上传到sae后，site-package/werobot/**init**.py 中的
from werobot.robot import WeRoBot 这条语句错误， 但是sys.path中已经包含有site-package目录了，不知道为啥会出现ImportError， 你看下能不能找到什么思路，我暂时没办法了

**Comment by zct** [comment]
解决了
是有robot.py 中的 import six 引起的
简单说来，就是加入正确的这条路径  sys.path.insert(1, os.path.join(root, 'lib/python2.7/site-packages'))

**Comment by tolerious** [comment]
good

**Comment by saneek** [comment]
@ZCT 好像我加了这个路径还是一样的错误，方便加我qq稍微指导一下吗？316921630谢谢
