### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by oxidegit** [whtsky/WeRoBot-SAE-demo#5]
window平台 python2.7 用git部署到sae上

我最开始的时候，是直接将这些代码连同werobot包一起部署到sae,可以访问url显示页面，但是微信端一直显示token验证失败。
然后我翻看了issue，里面有个人也是直接部署代码的，我看到你的回复是让按着命令来。

我在执行pip install sae-python-dev 这个命令的时候 出现了一些错误
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LENOVO~1\AppData\Local\Temp\pip-build-0dwl1ywa\sqlcmd\se
tup.py", line 25, in <module>
        info = loadInfo()
      File "C:\Users\LENOVO~1\AppData\Local\Temp\pip-build-0dwl1ywa\sqlcmd\se
tup.py", line 19, in loadInfo
        for line in open(os.path.join(here, 'sqlcmd', '__init__.py'), 'r'):
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa9 in position 429: i
llegal multibyte sequence

Command "python setup.py egg_info" failed with error code 1 in C:\Users\LENOVO~1\AppData\Local\Temp\pip-build-0dwl1y
wa\sqlcmd\

不知道该怎么处理，希望能得到您的一点帮助，感激不尽。

**Comment by whtsky** [comment]
不知道唉，建议联系 SAE 方的技术支持……
